import Navbar from '@/components/Navbar';


export const metadata = {
  title: 'Kết nối việc làm - Tài khoản của bạn',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <main className='min-h-screen flex flex-col justify-center items-center bgCover pt-16 text-white gap-5'>
      
      {children}
    </main>
  )
}
