
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';


export const metadata = {
  title: 'Kết nối việc làm - Admin page',
  description: 'Generated by create next app',
}

export default async function Layout({ children }) {
  const session = await getServerSession(authOptions);
  let mainClass = "min-h-screen flex flex-col justify-center items-center text-white gap-5 bgCover";

  if (session?.user ) {
    mainClass = "bg-lightGray min-h-screen"
  }

  return (
    <main className={mainClass} style={{ paddingTop: '70px' }}>

      {children}

    </main>
  )
}
