import Logo from '@/components/ui/logo';
import Footer from '@/components/client/ui/footer';
import Header from '@/components/client/ui/header';
import Navbar from '@/components/client/ui/navbar';


export const metadata = {
    title: 'Kết nối việc làm - Tài khoản của bạn',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <>
            <main className="main-content z-10 min-h-screen flex flex-col">
                <Header />
                <Navbar />
                <div className="flex flex-col justify-center items-center color-black gap-5 styleLight grow">
                    <div className='p-10 min-w-min max-w-full w-screen md:w-2/3 lg:w-1/3'>
                        <div className="mb-4 text-center">
                            <Logo href="/" />
                        </div>
                        {children}
                    </div>
                </div>
            </main>
            <Footer />
        </>
    )
}
