
import 'bootstrap/dist/css/bootstrap.css';
import '@/styles/globals.css';
import '@/app/styles.css';
import { Toaster } from '@/components/ui/toaster';
import Provider from '@/components/Provider';
import Footer from '@/components/client/ui/footer';

export const metadata = {
  title: 'Kết nối việc làm',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
      
            {children}
          {/* <main className='min-h-screen flex flex-col justify-center items-center'>
            <Navbar />
            {children}
          </main> */}
          <Toaster />
        
        </Provider>
      </body>
    </html>
  )
}
