
import Footer from '@/components/client/ui/footer';

export const metadata = {
  title: 'Kết nối việc làm',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  return (
    <>
      <main className="main-content z-10 min-h-screen">
        {children}
      </main>
      <Footer />
    </>
  )
}
